config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root 'posts#index'
get 'posts/new' => 'posts#new'
get 'posts/spring' => 'posts#spring'
get 'posts/summer' => 'posts#summer'
get 'posts/autumn' => 'posts#autumn'
get 'posts/winter' => 'posts#winter'
get 'posts/personal' => 'posts#personal'
post 'posts/result' => 'posts#result'
get 'posts/result' => 'posts#result'
get 'posts/all' => 'posts#all'
resources :users, only: [:show] 
 resources :posts do
  resources :likes, only: [:create, :destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :posts, dependent: :destroy #追記 ユーザーが削除されたら、ツイートも削除されるようになります。すでに書いてある場合は追記しなくて大丈夫です。
  validates :name, presence: true #追記
  validates :profile, length: { maximum: 200 } #追記

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/color_controller.rb
class ColorController < ApplicationController
    def index
    end

    def link
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/personal_controller.rb
# $(function() {
#     $('input:checkbox').change(function() {
#         var cnt = $('#q input:checkbox:checked').length;
#         $('div.result').text('選択：' + cnt + '個');
#     }).trigger('change');
# });
# </script>
class PersonalController < ApplicationController
    def index
    end

    def result
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
    def all
      @alls = Post.all.page(params[:page]).per(6)
    end

    def new
        @post = Post.new
    end

    def spring
      @springs = Post.where(season: 1)
      @springs= Post.where(season: 1).page(params[:page]).per(6)
    end
    def summer
      @summers= Post.where(season: 2)
      @summers= Post.where(season: 2).page(params[:page]).per(6)
    end
    def autumn
      @autumns= Post.where(season: 3)
      @autumns= Post.where(season: 3).page(params[:page]).per(6)
    end
    def winter
      @winters= Post.where(season: 4)
      @winters= Post.where(season: 4).page(params[:page]).per(6)
    end
   
    def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save and @post.season == 1
        redirect_to :action => "spring"
    elsif @post.save and @post.season == 2
        redirect_to :action => "summer"
    elsif @post.save and @post.season == 3
        redirect_to :action => "autumn"
    elsif @post.save and @post.season == 4
        redirect_to :action => "winter"    
    else
        redirect_to :action => "index"
    end
end


def result
  @nA = 0
  @nB = 0
  @nC = 0
  @nD = 0
  for i in 1..11 do
    if params[:"r#{i}"] == "A"
      @nA = @nA + 1
    elsif params[:"r#{i}"] == "B"
      @nB = @nB + 1
    elsif params[:"r#{i}"] == "C"
      @nC = @nC + 1
    elsif params[:"r#{i}"] == "D"
      @nD = @nD + 1
    end
  end
  render action:"result"
end
          


      def show
        @post = Post.find(params[:id])
      end

      def edit
        @post = Post.find(params[:id])
      end

      def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
          redirect_to :action => "show", :id => @post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
         post = Post.find(params[:id])
         post.destroy
          redirect_to action: :all
      end
    
      private
      def post_params
        params.require(:post).permit(:user_name,:body,:color,:image,:season)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/color_helper.rb
module ColorHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorMeHappy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
   <header>
  
    <div class="header-list">
    <nav class="menu">
    <input type="checkbox" href="#" class="menu-open" name="menu-open" id="menu-open"/>
    <label class="menu-open-button" for="menu-open">
      <span class="hamburger hamburger-1"></span>
      <span class="hamburger hamburger-2"></span>
      <span class="hamburger hamburger-3"></span>
    </label>
    <% if user_signed_in? %>
    <%= link_to user_path(current_user.id),class:"menu-item" do %>
      <i class="fas fa-user "></i></a>
      <% end %>
    <% else %>
    <%= link_to new_user_session_path,class:"menu-item" do %>
      <i class="fas fa-sign-in-alt "></i></a>
      <% end %>
    <% end %>
    
    <%= link_to posts_new_path,class:"menu-item" do %>
      <i class="fas fa-folder-plus "></i></a>
      <% end %>
    
   <%= link_to posts_all_path,class:"menu-item" do %>
        <i class="fas fa-camera-retro"></i></a>
        <% end %> 

        <%= link_to root_path,class:"menu-item" do %>
          <i class="fas fa-home"></i></a>
          <% end %> 
    
    
  </nav>
  
  <!-- filters -->
  <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
      <defs>
        <filter id="shadowed-goo">
            
            <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
            <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
            <feGaussianBlur in="goo" stdDeviation="3" result="shadow" />
            <feColorMatrix in="shadow" mode="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 -0.2" result="shadow" />
            <feOffset in="shadow" dx="1" dy="1" result="shadow" />
            <feComposite in2="shadow" in="goo" result="goo" />
            <feComposite in2="goo" in="SourceGraphic" result="mix" />
        </filter>
        <filter id="goo">
            <feGaussianBlur in="SourceGraphic" result="blur" stdDeviation="10" />
            <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
            <feComposite in2="goo" in="SourceGraphic" result="mix" />
        </filter>
      </defs>
  </svg>

     
  </div>
</header>
<main>
      <%= yield %>
</main>
<footer>
     <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
 </body>
</html>

app/views/posts/all.html.erb


<div class="all">
<div class="spa"> </div><br>
<h3>all posts</h3><br>
<div class="lin">
<%= link_to 'spring・', :controller => "posts", :action => "spring" %>
  <%= link_to 'summer・', :controller => "posts", :action => "summer" %>
  <%= link_to 'autumn・', :controller => "posts", :action => "autumn" %>
  <%= link_to 'winter', :controller => "posts", :action => "winter" %>
</div>
<%= page_entries_info @alls %>
<div class="posts-container">
  <% @alls.each do |p| %>
    <div class="post">
    <%= image_tag p.image_url, size: "250x200" if p.image? %><br>
    <% if user_signed_in? %>
       <% if current_user.already_liked?(p) %>
          <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% else %>
          <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
            <i class="far fa-heart"></i><%= p.likes.count %>
            <% end %>
       <% end %>
       <% else %>
       <i class="far fa-heart"></i><%= p.likes.count %>
  
      <% end %>
    <a href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
      <%= p.body %><br>
    
      <%= I18n.l p.created_at, format: :short %><br>
      
      
  
  
      <%= link_to "more", post_path(p.id) %>
      <% if user_signed_in? && current_user.id == p.user_id %>  
       <%= link_to "edit", edit_post_path(p.id) %>
       <%= link_to "delete", post_path(p.id), method: :delete %>
      <% end %> 　　
      </div>
    
  <% end %>
</div>
<div class="page">
<%= paginate @alls %></div>
</div>

app/views/posts/autumn.html.erb
<div class="autumn">
<div class="spa"> </div><br>
<h3>autumn</h3>
<div class="lin">
<%= link_to 'all・', :controller => "posts", :action => "all" %>
<%= link_to 'spring・', :controller => "posts", :action => "spring" %>
  <%= link_to 'summer・', :controller => "posts", :action => "summer" %>
  <%= link_to 'autumn・', :controller => "posts", :action => "autumn" %>
  <%= link_to 'winter・', :controller => "posts", :action => "winter" %>
</div>
  <div class="posts-container">
  <% @autumns.each do |p| %>
      <div class="post">
      <%= image_tag p.image_url, size: "250x200" if p.image? %><br>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(p) %>
            <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
              <i class="far fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% end %>
     
        
        
    <% else %>
    <i class="far fa-heart"></i><%= p.likes.count %>
    <% end %>
    <a href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
    <%= p.body %><br>
    <%= I18n.l p.created_at, format: :short %><br>
        <%= link_to "more", post_path(p.id) %>
        <% if user_signed_in? && current_user.id == p.user_id %>  
         <%= link_to "edit", edit_post_path(p.id) %>
         <%= link_to "delete", post_path(p.id), method: :delete %>
        <% end %> 　　
        </div>
      
    <% end %>
    </div>
    <%= page_entries_info @autumns %>
<%= paginate @autumns %>
</div>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
 
  <div class="sub">
  <div class="spa"> </div><br>
  <h3> e d i t</h3>
   <div class="title">
     <%= f.label :image %> </div><br>
     <div class="fiel1">
     <%= image_tag @post.image.url %><br>
     <%= f.file_field :image, class: "image"%>
   </div>
 
   <div class="title">
     <%= f.label :text %></div><br>
     <br>
     <div class="field2">
     <%= f.text_area :body, :size => 100 %>

    <div class="botan">
    <%= f.submit "編集する" %></div>
  <% end %>
  </div>
  

app/views/posts/index.html.erb

<div class="image1">
<img src="assets/1.png">
<p>ー自分色を見つけようー</p>
</div>

<div class="happy">
<P>color<br> me happy</p>
</div>



<br>
<div class="image3">
<img src="assets/po2.png">
</div>
<br>
<div class="image4">
<img src="assets/po.png">
</div>

<div class="judge">
 <div class="image2">
 <a href="/posts/personal.html"><img src="assets/2.png"></a>
 <p>please click me!</p>
 </div>
 <div class="judge-name">
  <span>at first</span><br>
  パーソナルカラー診断
 </div>
</div>

<li><%= link_to "ログイン", new_user_session_path %></li>

app/views/posts/new.html.erb
<div class="sub">
<div class="spa"> </div><br>
<h3>new post</h3>

<%= form_for @post do |f| %>
 
 
  <div class="title">
    <%= f.label :image %> </div><br>
    <div class="field1">
    <%= f.file_field :image, class: "image"%>
  </div>

  <div class="title">
    <%= f.label :text %></div><br>
    <br>
    <div class="field2">
    <%= f.text_area :body, :size => 100 %>
  </div>
  <br>
  <div class "pulld">
  <%= f.select :season, [["spring", "1"], ["summer", "2"], ["autumn", "3"], ["winter", "4"]], include_blank: "パーソナルカラー" %><br>
 </div>
  <%= f.submit "投稿する" %>
<% end %>
<div class="lin3">
<%= link_to "投稿一覧に戻る", posts_path %></div>
</div>

app/views/posts/show.html.erb
<div class="showall">
<div class="spa"> </div><br>
<h3>more...</h3>
<div class="show">
<div class="post">
 <p>
 <%= image_tag @post.image_url,:size => '200×200' %>
 </p>
 <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
          <%= link_to post_like_path(@post), method: :delete do %>
            <i class="fas fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(@post), method: :post do %>
            <i class="far fa-heart"></i><%= @post.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= @post.likes.count %>
  <% end %>

 <%= @post.user.name %>
 <p><%= @post.body %></p>

  <p><%= I18n.l @post.created_at, format: :short %></p>

  
</div>
<div claaa="iine">
<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>
<div>

</div>

<div class="lin2">
<%= link_to "投稿一覧へ", posts_all_path %><br>
<%= link_to "編集する", edit_post_path(@post.id) %>
</div>
</div>

app/views/posts/spring.html.erb

<div class="spring">
<div class="spa"> </div><br>
<h3>spring</h3>
<div class="lin">
<%= link_to 'all・', :controller => "posts", :action => "all" %>
<%= link_to 'spring・', :controller => "posts", :action => "spring" %>
  <%= link_to 'summer・', :controller => "posts", :action => "summer" %>
  <%= link_to 'autumn・', :controller => "posts", :action => "autumn" %>
  <%= link_to 'winter・', :controller => "posts", :action => "winter" %>
  </div>

  <%= page_entries_info @springs %>
<div class="posts-container">
<% @springs.each do |p| %>
  <div class="post">
  <%= image_tag p.image_url, size: "250x200" if p.image? %><br>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(p) %>
        <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= p.likes.count %>
        <% end %>
    <% else %>
        <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
          <i class="far fa-heart"></i><%= p.likes.count %>
        <% end %>
    <% end %>
 
<% else %>
<i class="far fa-heart"></i><%= p.likes.count %>
<% end %>
<a href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
<%= p.body %><br>
<%= I18n.l p.created_at, format: :short %><br>
    <%= link_to "more", post_path(p.id) %>
    <% if user_signed_in? && current_user.id == p.user_id %>  
     <%= link_to "edit", edit_post_path(p.id) %>
     <%= link_to "delete", post_path(p.id), method: :delete %>
    <% end %> 　　
    </div>
  
<% end %>
</div>
<%= paginate @springs %>
</div>




app/views/posts/summer.html.erb
<div class="summer">
<div class="spa"> </div><br>
<h3>summer</h3>
<div class="lin">
<%= link_to 'all・', :controller => "posts", :action => "all" %>
<%= link_to 'spring・', :controller => "posts", :action => "spring" %>
  <%= link_to 'summer・', :controller => "posts", :action => "summer" %>
  <%= link_to 'autumn・', :controller => "posts", :action => "autumn" %>
  <%= link_to 'winter・', :controller => "posts", :action => "winter" %>
</div>

  <div class="posts-container">
  <% @summers.each do |p| %>
      <div class="post">
      <%= image_tag p.image_url, size: "250x200" if p.image? %><br>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(p) %>
            <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
              <i class="far fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% end %>
      
        
    <% else %>
    <i class="far fa-heart"></i><%= p.likes.count %>
    <% end %>
    <a href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
        <%= p.body %><br>
        <%= I18n.l p.created_at, format: :short %><br>
        
        <%= link_to "more", post_path(p.id) %>
        <% if user_signed_in? && current_user.id == p.user_id %>  
         <%= link_to "edit", edit_post_path(p.id) %>
         <%= link_to "delete", post_path(p.id), method: :delete %>
        <% end %> 　　
        </div>
      
    <% end %>
    </div>
 <%= page_entries_info @summers %>
<%= paginate @summers %>
</div>

app/views/posts/winter.html.erb
<div class="winter">
<div class="spa"> </div><br>
<h3>winter</h3>
<div class="lin">
<%= link_to 'all・', :controller => "posts", :action => "all" %>
<%= link_to 'spring・', :controller => "posts", :action => "spring" %>
  <%= link_to 'summer・', :controller => "posts", :action => "summer" %>
  <%= link_to 'autumn・', :controller => "posts", :action => "autumn" %>
  <%= link_to 'winter', :controller => "posts", :action => "winter" %>
<div class="tra">
 <%= page_entries_info @winters %></div>
 </div>
 
  <div class="posts-container">
  <% @winters.each do |p| %>
      <div class="post">
      <%= image_tag p.image_url, size: "250x200" if p.image? %><br>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(p) %>
            <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% else %>
            <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
              <i class="far fa-heart"></i><%= p.likes.count %>
            <% end %>
        <% end %>
      
        
        
    <% else %>
    <i class="far fa-heart"></i><%= p.likes.count %>
    <% end %>
    <a href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
        <%= p.body %><br>
        <%= I18n.l p.created_at, format: :short %><br>
        <%= link_to "more", post_path(p.id) %>
        <% if user_signed_in? && current_user.id == p.user_id %>  
         <%= link_to "edit", edit_post_path(p.id) %>
         <%= link_to "delete", post_path(p.id), method: :delete %>
        <% end %> 　　
        </div>
      
    <% end %>
    </div>
<%= paginate @winters %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="maall">
<div class="spa"> </div><br>
<div class="mypa">
<h5>User page</h5>
<p>name : <%= @user.name %></p>
<p>adress : <%= @user.email %></p>
<p>profile : <%= @user.profile %></p>
<div class="lin">
<% if current_user.id == @user.id %>

  <%= link_to " edit", edit_user_registration_path , class:"fas fa-edit" %><br>
  <%= link_to 'sign out', destroy_user_session_path, method: :delete , class:"fas fa-sign-out-alt" %>
<% end %>
<div class="spa"> </div><br>
</div>
</div>
 <br>
 <h6>-Users posts-</h6>
 <div class="posts-container">
  
<% @user.posts.each do |p| %>
  <% if user_signed_in? && current_user.id == p.user_id %> 
  <div class="post">
  <%= image_tag p.image_url, size: "250x200" if p.image? %><br>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(p) %>
        <%= link_to post_like_path(id: p.id, post_id: p.id), method: :delete do %>
          <i class="fas fa-heart"></i><%= p.likes.count %>
        <% end %>
    <% else %>
        <%= link_to post_likes_path(id: p.id, post_id: p.id), method: :post do %>
          <i class="far fa-heart"></i><%= p.likes.count %>
        <% end %>
    <% end %>
  <a href="/users/<%= p.user.id %>"><%= p.user.name %></a><br>
    <%= p.body %><br>
  
    <%= I18n.l p.created_at, format: :short %><br>
    
    
<% else %>
<i class="far fa-heart"></i><%= p.likes.count %>
<% end %>
    <%= link_to "more", post_path(p.id) %>
    <% if user_signed_in? && current_user.id == p.user_id %>  
     <%= link_to "edit", edit_post_path(p.id) %>
     <%= link_to "delete", post_path(p.id), method: :delete %>
    <% end %> 　　
    </div>
 
<% end %>
<% end %>

</div>
<div class="lin">
<%= link_to "投稿一覧に戻る", posts_all_path %></div>

</div>

</div>